# Generated by Django 3.2.9 on 2022-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('writer', 'writer')], default='admin', max_length=200),
        ),
    ]
